package com.jwzt.DB.cdn.ip_manage;
// Generated 2006-6-6 14:24:15 by Hibernate Tools 3.1.0 beta3

/**
 * IpSegmentInfo generated by hbm2java
 */

public class IpSegmentInfo  implements java.io.Serializable 
{
     /**
      * ip ID
     */
     private Integer ip_id;
     /**
      * IP地址表id
     */
     private IpAddressInfo ipAddressInfo;
     /**
      * 起始ip地址值
     */
     private String ip_start;
     /**
      * 结束ip地址
     */
     private String ip_end;
     /**
      * 开始ip地址值
     */
     private Long ip_start_value;
     /**
      * 结束ip地址值
     */
     private Long ip_end_value;
     


    // Constructors

    /** default constructor */
    public IpSegmentInfo() {
    }

	/** minimal constructor */
    public IpSegmentInfo(Integer ip_id) {
        this.ip_id = ip_id;
    }

	public String getIp_end() {
		return ip_end;
	}

	public void setIp_end(String ip_end) {
		this.ip_end = ip_end;
	}

	public Long getIp_end_value() {
		return ip_end_value;
	}

	public void setIp_end_value(Long ip_end_value) {
		this.ip_end_value = ip_end_value;
	}

	public Integer getIp_id() {
		return ip_id;
	}

	public void setIp_id(Integer ip_id) {
		this.ip_id = ip_id;
	}

	public String getIp_start() {
		return ip_start;
	}

	public void setIp_start(String ip_start) {
		this.ip_start = ip_start;
	}

	public Long getIp_start_value() {
		return ip_start_value;
	}

	public void setIp_start_value(Long ip_start_value) {
		this.ip_start_value = ip_start_value;
	}

	public IpAddressInfo getIpAddressInfo() {
		return ipAddressInfo;
	}

	public void setIpAddressInfo(IpAddressInfo ipAddressInfo) {
		this.ipAddressInfo = ipAddressInfo;
	}
    
    
}
