package com.jwzt.DB.soms.live.liveChannel;

// Generated 2006-6-6 14:24:16 by Hibernate Tools 3.1.0 beta3

import java.sql.Timestamp;

/**
 * ChannelInfo generated by hbm2java
 */

public class ChannelInfo implements java.io.Serializable
{

	// Fields

	/**
	 * 唯一ID
	 */
	private Integer channel_id;

	/**
	 * 频道名称
	 */
	private String channel_name;

	/**
	 * 频道所属的电视台（备用）
	 */
	private Integer channel_group_id;

	/**
	 * 直播发布点所在的服务器组ID
	 */
	private Integer pub_server_group;
	/**
	 * 时移-直播发布点所在的服务器组ID
	 */
	private Integer pub_server_group_sy;
	/**
	 * m3u8-直播发布点所在的服务器组ID
	 */
	private Integer pub_server_group_ts;

	/**
	 * 直播切片文件存储目录
	 */
	private String file_save_directory_sy="";
	
	

	/**
	 * TS直播切片文件存储目录
	 */
	private String file_save_directory_ts="";

	/**
	 * 直播发布点名称
	 */
	private String channel_mount_name;

	/**
	 * 频道类型 0：采集直播 1：虚拟直播 2：混和直播(单码流) 3：混和直播(多码流)
	 */
	private Integer channel_type;

	/**
	 * 上传服务器地址（发布点ID）
	 */
	private Integer upload_mount_id;

	/**
	 * 配置文件id （根据配置文件判断是视频还是音频）
	 */
	private Integer profile_id;

	/**
	 * 频道描述
	 */
	private String channel_desc;

	/**
	 * 是否加密（0：不加密 1：加密）
	 */
	private Integer if_drm;

	/**
	 * 直播认证地址
	 */
	private String drm_address;

	/**
	 * 0：推；1：拉
	 */
	private Integer isPost;

	/**
	 * 拉、推方式的端口
	 */
	private Integer port;

	/**
	 * 拉方式采集工作站的ip地址
	 */
	private String encoder_address;

	/**
	 * 远程发布点地址
	 */
	private String remote_mount_url;

	/**
	 * 用户名
	 */
	private String user_name;

	/**
	 * 密码
	 */
	private String user_pwd;

	/**
	 * 是否支持标清 0不支持，1支持
	 */
	private String sub_server_groups;

	/**
	 * 采集时视频流中的作者
	 */
	private String channel_author;

	/**
	 * 采集时视频流中的标题
	 */
	private String channel_title;

	/**
	 * 采集时视频流的比特率
	 */
	private String channel_bit;

	/**
	 * 采集时视频流的版权
	 */
	private String channel_rights;

	/**
	 * 采集时视频流中的描述
	 */
	private String channel_tv_desc;

	/**
	 * 频道节目的展现方式 0：由节目生成节目单 1：静态节目单
	 */
	private Integer program_list_type;

	/**
	 * 频道的直播状态 0：不正常 1：正常
	 */
	private Integer channel_state;

	/**
	 * 是否停止直播 0：停止 1：开启
	 */
	private Integer channel_switch;

	/**
	 * 是否更新配置（和c交互时，用该字段判断频道是否更新）
	 */
	private Integer if_refresh = 0;

	/**
	 * 记录生成频道时间
	 */
	private Timestamp record_time;
	/**
	 * 频道直播流的类型 ：1.wmv 2.flv 3.f4v 4.ts
	 */
	private Integer stream_type;

	
	/**
	 * 频道显示名称
	 */
	private String channel_show_name;
	
	/**
	 * 是否允许互动
	 */
	private Integer is_chat_button;
	
	/**
	 * LOGO图片
	 */
	private String channel_logo_pic;
	
	/**
	 * 频道是否需要审核
	 */
	private int channel_if_checked;

	
	
	/**
	 * TS直播切片文件存储目录
	 */
	private String live_pub="";
	
	/**
	 * 频道排序
	 */
	private Integer chann_order=100;
	/**
	 * 直播频道图片
	 */
	private String chann_pic="";
	/**
	 * 直播地址HTTP
	 */
	private String chann_streaming="";
	/**
	 * 直播地址RTMP
	 */
	private String chann_streaming_rtmp="";
	/**
	 * 直播地址HLS M3U8
	 */
	private String chann_streaming_hls="";
	
	public String getLive_pub() {
		return live_pub;
	}

	public void setLive_pub(String live_pub) {
		this.live_pub = live_pub;
	}
	
	// Constructors

	/** default constructor */
	public ChannelInfo()
	{
	}

	/** minimal constructor */
	public ChannelInfo(Integer channel_id, String channel_name,
			Integer channel_type, String drm_address, String user_name)
	{
		this.channel_id = channel_id;
		this.channel_name = channel_name;
		this.channel_type = channel_type;
		this.drm_address = drm_address;
		this.user_name = user_name;
	}

	/** full constructor */
	public ChannelInfo(Integer channel_id, String channel_name,
			Integer channel_group_id, Integer pub_server_group, 
			Integer pub_server_group_sy, Integer pub_server_group_ts,String file_save_directory_sy,String file_save_directory_ts,
			String channel_mount_name, Integer channel_type,
			Integer upload_mount_id, Integer profile_id, String channel_desc,
			Integer if_drm, String drm_address, Integer isPost, Integer port,
			String encoder_address, String remote_mount_url, String user_name,
			String user_pwd, String sub_server_groups, String channel_author,
			String channel_title, String channel_bit, String channel_rights,
			String channel_tv_desc, Integer program_list_type,
			Integer channel_state, Integer channel_switch, Integer if_refresh,
			Timestamp record_time,Integer stream_type)
	{
		this.channel_id = channel_id;
		this.channel_name = channel_name;
		this.channel_group_id = channel_group_id;
		this.pub_server_group = pub_server_group;
		this.pub_server_group_sy=pub_server_group_sy;
		this.pub_server_group_ts=pub_server_group_ts;
		this.file_save_directory_sy=file_save_directory_sy;
		this.file_save_directory_ts=file_save_directory_ts;
		this.channel_mount_name = channel_mount_name;
		this.channel_type = channel_type;
		this.upload_mount_id = upload_mount_id;
		this.profile_id = profile_id;
		this.channel_desc = channel_desc;
		this.if_drm = if_drm;
		this.drm_address = drm_address;
		this.isPost = isPost;
		this.port = port;
		this.encoder_address = encoder_address;
		this.remote_mount_url = remote_mount_url;
		this.user_name = user_name;
		this.user_pwd = user_pwd;
		this.sub_server_groups = sub_server_groups;
		this.channel_author = channel_author;
		this.channel_title = channel_title;
		this.channel_bit = channel_bit;
		this.channel_rights = channel_rights;
		this.channel_tv_desc = channel_tv_desc;
		this.program_list_type = program_list_type;
		this.channel_state = channel_state;
		this.channel_switch = channel_switch;
		this.if_refresh = if_refresh;
		this.record_time = record_time;
		this.stream_type = stream_type;
		
	}

	// Property accessors
	/**
	 * * 唯一ID
	 */

	public Integer getChannel_id()
	{
		return this.channel_id;
	}

	public void setChannel_id(Integer channel_id)
	{
		this.channel_id = channel_id;
	}

	/**
	 * * 频道名称
	 */

	public String getChannel_name()
	{
		return this.channel_name;
	}

	public void setChannel_name(String channel_name)
	{
		this.channel_name = channel_name;
	}

	/**
	 * * 频道所属的电视台（备用）
	 */

	public Integer getChannel_group_id()
	{
		return this.channel_group_id;
	}

	public void setChannel_group_id(Integer channel_group_id)
	{
		this.channel_group_id = channel_group_id;
	}

	/**
	 * * 直播发布点所在的服务器组ID
	 */

	public Integer getPub_server_group()
	{
		return this.pub_server_group;
	}

	public void setPub_server_group(Integer pub_server_group)
	{
		this.pub_server_group = pub_server_group;
	}

	/**
	 * * 直播发布点名称
	 */

	public String getChannel_mount_name()
	{
		return this.channel_mount_name;
	}

	public void setChannel_mount_name(String channel_mount_name)
	{
		this.channel_mount_name = channel_mount_name;
	}

	/**
	 * * 频道类型 0：采集直播 1：虚拟直播 2：混和直播
	 */

	public Integer getChannel_type()
	{
		return this.channel_type;
	}

	public void setChannel_type(Integer channel_type)
	{
		this.channel_type = channel_type;
	}

	/**
	 * * 上传服务器地址（发布点ID）
	 */

	public Integer getUpload_mount_id()
	{
		return this.upload_mount_id;
	}

	public void setUpload_mount_id(Integer upload_mount_id)
	{
		this.upload_mount_id = upload_mount_id;
	}

	/**
	 * * 配置文件id （根据配置文件判断是视频还是音频）
	 */

	public Integer getProfile_id()
	{
		return this.profile_id;
	}

	public void setProfile_id(Integer profile_id)
	{
		this.profile_id = profile_id;
	}

	/**
	 * * 频道描述
	 */

	public String getChannel_desc()
	{
		return this.channel_desc;
	}

	public void setChannel_desc(String channel_desc)
	{
		this.channel_desc = channel_desc;
	}

	/**
	 * * 是否加密（0：不加密 1：加密）
	 */

	public Integer getIf_drm()
	{
		return this.if_drm;
	}

	public void setIf_drm(Integer if_drm)
	{
		this.if_drm = if_drm;
	}

	/**
	 * * 直播认证地址
	 */

	public String getDrm_address()
	{
		return this.drm_address;
	}

	public void setDrm_address(String drm_address)
	{
		this.drm_address = drm_address;
	}

	/**
	 * * 1：推；0：拉
	 */

	public Integer getIsPost()
	{
		return this.isPost;
	}

	public void setIsPost(Integer isPost)
	{
		this.isPost = isPost;
	}

	/**
	 * * 拉、推方式的端口
	 */

	public Integer getPort()
	{
		return this.port;
	}

	public void setPort(Integer port)
	{
		this.port = port;
	}

	/**
	 * * 拉方式采集工作站的ip地址
	 */

	public String getEncoder_address()
	{
		return this.encoder_address;
	}

	public void setEncoder_address(String encoder_address)
	{
		this.encoder_address = encoder_address;
	}

	/**
	 * * 远程发布点地址
	 */

	public String getRemote_mount_url()
	{
		return this.remote_mount_url;
	}

	public void setRemote_mount_url(String remote_mount_url)
	{
		this.remote_mount_url = remote_mount_url;
	}

	/**
	 * * 用户名
	 */

	public String getUser_name()
	{
		return this.user_name;
	}

	public void setUser_name(String user_name)
	{
		this.user_name = user_name;
	}

	/**
	 * * 密码
	 */

	public String getUser_pwd()
	{
		return this.user_pwd;
	}

	public void setUser_pwd(String user_pwd)
	{
		this.user_pwd = user_pwd;
	}

	/**
	 * * 是否支持标清 0不支持，1支持
	 */

	public String getSub_server_groups()
	{
		return this.sub_server_groups;
	}

	/**
	 * * 是否支持标清 0不支持，1支持
	 */
	public void setSub_server_groups(String sub_server_groups)
	{
		this.sub_server_groups = sub_server_groups;
	}

	/**
	 * * 采集时视频流中的作者
	 */

	public String getChannel_author()
	{
		return this.channel_author;
	}

	public void setChannel_author(String channel_author)
	{
		this.channel_author = channel_author;
	}

	/**
	 * * 采集时视频流中的标题
	 */

	public String getChannel_title()
	{
		return this.channel_title;
	}

	public void setChannel_title(String channel_title)
	{
		this.channel_title = channel_title;
	}

	/**
	 * * 采集时视频流的比特率
	 */

	public String getChannel_bit()
	{
		return this.channel_bit;
	}

	public void setChannel_bit(String channel_bit)
	{
		this.channel_bit = channel_bit;
	}

	/**
	 * * 采集时视频流的版权
	 */

	public String getChannel_rights()
	{
		return this.channel_rights;
	}

	public void setChannel_rights(String channel_rights)
	{
		this.channel_rights = channel_rights;
	}

	/**
	 * * 采集时视频流中的描述
	 */

	public String getChannel_tv_desc()
	{
		return this.channel_tv_desc;
	}

	public void setChannel_tv_desc(String channel_tv_desc)
	{
		this.channel_tv_desc = channel_tv_desc;
	}

	/**
	 * * 频道节目的展现方式 0：由节目生成节目单 1：静态节目单
	 */

	public Integer getProgram_list_type()
	{
		return this.program_list_type;
	}

	public void setProgram_list_type(Integer program_list_type)
	{
		this.program_list_type = program_list_type;
	}

	/**
	 * * 频道的直播状态 0：不正常 1：正常
	 */

	public Integer getChannel_state()
	{
		return this.channel_state;
	}

	public void setChannel_state(Integer channel_state)
	{
		this.channel_state = channel_state;
	}

	/**
	 * * 是否停止直播 0：停止 1：开启
	 */

	public Integer getChannel_switch()
	{
		return this.channel_switch;
	}

	public void setChannel_switch(Integer channel_switch)
	{
		this.channel_switch = channel_switch;
	}

	public Integer getStream_type() {
		return stream_type;
	}

	public void setStream_type(Integer stream_type) {
		this.stream_type = stream_type;
	}

	/**
	 * * 是否更新配置（和c交互时，用该字段判断频道是否更新）
	 */

	public Integer getIf_refresh()
	{
		return this.if_refresh;
	}

	public void setIf_refresh(Integer if_refresh)
	{
		this.if_refresh = if_refresh;
	}

	/**
	 * * 记录生成频道时间
	 */

	public Timestamp getRecord_time()
	{
		return this.record_time;
	}

	public void setRecord_time(Timestamp record_time)
	{
		this.record_time = record_time;
	}
	
	public static int DEVICE_LIVE = 0;
	public static int DEVICE_LIVE_PUSH = 0;
	public static int DEVICE_LIVE_PULL = 1;
	public static int FILE_LIVE = 1;
	public static int Device_And_File_Live_Single = 2;
	public static int Device_And_File_Live_Mulit = 3;


	/**
	 * @return the channel_show_name
	 */
	public String getChannel_show_name()
	{
		return channel_show_name;
	}

	/**
	 * @param channel_show_name the channel_show_name to set
	 */
	public void setChannel_show_name(String channel_show_name)
	{
		this.channel_show_name = channel_show_name;
	}

	/**
	 * @return the is_chat_button
	 */
	public Integer getIs_chat_button()
	{
		return is_chat_button;
	}

	/**
	 * @param is_chat_button the is_chat_button to set
	 */
	public void setIs_chat_button(Integer is_chat_button)
	{
		this.is_chat_button = is_chat_button;
	}

	/**
	 * @return the channel_logo_pic
	 */
	public String getChannel_logo_pic()
	{
		return channel_logo_pic;
	}

	/**
	 * @param channel_logo_pic the channel_logo_pic to set
	 */
	public void setChannel_logo_pic(String channel_logo_pic)
	{
		this.channel_logo_pic = channel_logo_pic;
	}

	/**
	 * @return the channel_if_checked
	 */
	public int getChannel_if_checked()
	{
		return channel_if_checked;
	}

	/**
	 * @param channel_if_checked the channel_if_checked to set
	 */
	public void setChannel_if_checked(int channel_if_checked)
	{
		this.channel_if_checked = channel_if_checked;
	}

	public Integer getPub_server_group_sy() {
		return pub_server_group_sy;
	}

	public void setPub_server_group_sy(Integer pub_server_group_sy) {
		this.pub_server_group_sy = pub_server_group_sy;
	}

	public Integer getPub_server_group_ts() {
		return pub_server_group_ts;
	}

	public void setPub_server_group_ts(Integer pub_server_group_ts) {
		this.pub_server_group_ts = pub_server_group_ts;
	}
	public String getFile_save_directory_sy() {
		return file_save_directory_sy;
	}

	public void setFile_save_directory_sy(String file_save_directory_sy) {
		this.file_save_directory_sy = file_save_directory_sy;
	}

	public String getFile_save_directory_ts() {
		return file_save_directory_ts;
	}

	public void setFile_save_directory_ts(String file_save_directory_ts) {
		this.file_save_directory_ts = file_save_directory_ts;
	}

	public Integer getChann_order() {
		return chann_order;
	}

	public void setChann_order(Integer chann_order) {
		this.chann_order = chann_order;
	}

	public String getChann_pic() {
		return chann_pic;
	}

	public void setChann_pic(String chann_pic) {
		this.chann_pic = chann_pic;
	}

	public String getChann_streaming() {
		return chann_streaming;
	}

	public void setChann_streaming(String chann_streaming) {
		this.chann_streaming = chann_streaming;
	}

	public String getChann_streaming_rtmp() {
		return chann_streaming_rtmp;
	}

	public void setChann_streaming_rtmp(String chann_streaming_rtmp) {
		this.chann_streaming_rtmp = chann_streaming_rtmp;
	}

	public String getChann_streaming_hls() {
		return chann_streaming_hls;
	}

	public void setChann_streaming_hls(String chann_streaming_hls) {
		this.chann_streaming_hls = chann_streaming_hls;
	}
}
