package com.jwzt.DB.cdn.serverGroup;
// Generated 2006-6-14 11:48:22 by Hibernate Tools 3.1.0 beta3

import com.jwzt.DB.cdn.region.RegionInfo;


/**
 * ServerGroupInfo generated by hbm2java
 */

public class ServerGroupInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 服务器组ID
     */
     private Integer server_group_id;
     /**
      * 服务器组区域ID
     */
     private RegionInfo server_region;
     /**
      * 服务器组名称
     */
     private String server_group_name;
     /**
      * 分发是否启动  0:关闭  1:启动
     */
     private Integer distribute_status;
     /**
      * 分发服务器组类型  0:中心服务器组  1:分发服务器组
     */
     private Integer server_group_type;
     /**
      * 服务器组地址
     */
     private String virtual_ip;
     /**
      * 磁盘空间  单位 G
     */
     private Integer disk_space;
     /**
      * 公共磁盘空间  单位 G
     */
     private Integer public_disk_space;
     /**
      * 警戒磁盘空间  单位 M
     */
     private Integer warning_space;
     /**
      * 剩余磁盘空间  单位 M
     */
     private Integer left_space;
     /**
      * 负载均衡策略 1:软件智能  2:软件随机  3：网络负载均衡
     */
     private Integer loadbalance_mode;
     /**
      * 是否监控 0:是  1:否
     */
     private Integer if_monitor;
     /**
      * 监控频率 30s
     */
     private Integer monitor_frequency;
     /**
      * 服务器组集群ID
     */
     private Integer logical_server_group_id;


    // Constructors

    /** default constructor */
    public ServerGroupInfo() {
    }

	/** minimal constructor */
    public ServerGroupInfo(Integer server_group_id) {
        this.server_group_id = server_group_id;
    }
    
    /** full constructor */
    public ServerGroupInfo(Integer server_group_id, RegionInfo server_region, String server_group_name, Integer distribute_status, Integer server_group_type, String virtual_ip, Integer disk_space, Integer public_disk_space, Integer warning_space, Integer left_space, Integer loadbalance_mode, Integer if_monitor, Integer monitor_frequency, Integer logical_server_group_id) {
        this.server_group_id = server_group_id;
        this.server_region = server_region;
        this.server_group_name = server_group_name;
        this.distribute_status = distribute_status;
        this.server_group_type = server_group_type;
        this.virtual_ip = virtual_ip;
        this.disk_space = disk_space;
        this.public_disk_space = public_disk_space;
        this.warning_space = warning_space;
        this.left_space = left_space;
        this.loadbalance_mode = loadbalance_mode;
        this.if_monitor = if_monitor;
        this.monitor_frequency = monitor_frequency;
        this.logical_server_group_id = logical_server_group_id;
    }
    

   
    // Property accessors
    /**       
     *      * 服务器组ID
     */

    public Integer getServer_group_id() {
        return this.server_group_id;
    }
    
    public void setServer_group_id(Integer server_group_id) {
        this.server_group_id = server_group_id;
    }
    /**       
     *      * 服务器组区域ID
     */

    public RegionInfo getServer_region() {
        return this.server_region;
    }
    
    public void setServer_region(RegionInfo server_region) {
        this.server_region = server_region;
    }
    /**       
     *      * 服务器组名称
     */

    public String getServer_group_name() {
        return this.server_group_name;
    }
    
    public void setServer_group_name(String server_group_name) {
        this.server_group_name = server_group_name;
    }
    /**       
     *      * 分发是否启动  0:关闭  1:启动
     */

    public Integer getDistribute_status() {
        return this.distribute_status;
    }
    
    public void setDistribute_status(Integer distribute_status) {
        this.distribute_status = distribute_status;
    }
    /**       
     *      * 分发服务器组类型  0:中心服务器组  1:分发服务器组
     */

    public Integer getServer_group_type() {
        return this.server_group_type;
    }
    
    public void setServer_group_type(Integer server_group_type) {
        this.server_group_type = server_group_type;
    }
    /**       
     *      * 服务器组地址
     */

    public String getVirtual_ip() {
        return this.virtual_ip;
    }
    
    public void setVirtual_ip(String virtual_ip) {
        this.virtual_ip = virtual_ip;
    }
    /**       
     *      * 磁盘空间  单位 G
     */

    public Integer getDisk_space() {
        return this.disk_space;
    }
    
    public void setDisk_space(Integer disk_space) {
        this.disk_space = disk_space;
    }
    /**       
     *      * 公共磁盘空间  单位 G
     */

    public Integer getPublic_disk_space() {
        return this.public_disk_space;
    }
    
    public void setPublic_disk_space(Integer public_disk_space) {
        this.public_disk_space = public_disk_space;
    }
    /**       
     *      * 警戒磁盘空间  单位 M
     */

    public Integer getWarning_space() {
        return this.warning_space;
    }
    
    public void setWarning_space(Integer warning_space) {
        this.warning_space = warning_space;
    }
    /**       
     *      * 剩余磁盘空间  单位 M
     */

    public Integer getLeft_space() {
        return this.left_space;
    }
    
    public void setLeft_space(Integer left_space) {
        this.left_space = left_space;
    }
    /**       
     *      * 负载均衡策略 1:软件智能  2:软件随机  3：网络负载均衡
     */

    public Integer getLoadbalance_mode() {
        return this.loadbalance_mode;
    }
    
    public void setLoadbalance_mode(Integer loadbalance_mode) {
        this.loadbalance_mode = loadbalance_mode;
    }
    /**       
     *      * 是否监控 0:是  1:否
     */

    public Integer getIf_monitor() {
        return this.if_monitor;
    }
    
    public void setIf_monitor(Integer if_monitor) {
        this.if_monitor = if_monitor;
    }
    /**       
     *      * 监控频率 30s
     */

    public Integer getMonitor_frequency() {
        return this.monitor_frequency;
    }
    
    public void setMonitor_frequency(Integer monitor_frequency) {
        this.monitor_frequency = monitor_frequency;
    }
    /**       
     *      * 服务器组集群ID
     */

    public Integer getLogical_server_group_id() {
        return this.logical_server_group_id;
    }
    
    public void setLogical_server_group_id(Integer logical_server_group_id) {
        this.logical_server_group_id = logical_server_group_id;
    }
   








}
