package com.jwzt.DB.soms.live.codeFlow;
// Generated 2006-6-6 14:24:16 by Hibernate Tools 3.1.0 beta3



/**
 * CodeFlowInfo generated by hbm2java
 */

public class CodeFlowInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一ID
     */
     private Integer codeflow_id;
     /**
      * 视频码流名称
     */
     private String codeflow_name;
     /**
      * 比特率
     */
     private Integer bit_rate;
     /**
      * 帧速率
     */
     private Integer fps;
     /**
      * 图像质量
     */
     private Integer video_quality;
     /**
      * 关键帧间隔
     */
     private Integer second_per_key;

     /**
 	 * 站点id
 	 */
 	private Integer site_id;

 	public Integer getSite_id() {
 		return site_id;
 	}

 	public void setSite_id(Integer site_id) {
 		this.site_id = site_id;
 	}

    // Constructors

    /** default constructor */
    public CodeFlowInfo() {
    }

	/** minimal constructor */
    public CodeFlowInfo(Integer codeflow_id, String codeflow_name) {
        this.codeflow_id = codeflow_id;
        this.codeflow_name = codeflow_name;
    }
    
    /** full constructor */
    public CodeFlowInfo(Integer codeflow_id, String codeflow_name, Integer bit_rate, Integer fps, Integer video_quality, Integer second_per_key) {
        this.codeflow_id = codeflow_id;
        this.codeflow_name = codeflow_name;
        this.bit_rate = bit_rate;
        this.fps = fps;
        this.video_quality = video_quality;
        this.second_per_key = second_per_key;
    }
    

   
    // Property accessors
    /**       
     *      * 唯一ID
     */

    public Integer getCodeflow_id() {
        return this.codeflow_id;
    }
    
    public void setCodeflow_id(Integer codeflow_id) {
        this.codeflow_id = codeflow_id;
    }
    /**       
     *      * 视频码流名称
     */

    public String getCodeflow_name() {
        return this.codeflow_name;
    }
    
    public void setCodeflow_name(String codeflow_name) {
        this.codeflow_name = codeflow_name;
    }
    /**       
     *      * 比特率
     */

    public Integer getBit_rate() {
        return this.bit_rate;
    }
    
    public void setBit_rate(Integer bit_rate) {
        this.bit_rate = bit_rate;
    }
    /**       
     *      * 帧速率
     */

    public Integer getFps() {
        return this.fps;
    }
    
    public void setFps(Integer fps) {
        this.fps = fps;
    }
    /**       
     *      * 图像质量
     */

    public Integer getVideo_quality() {
        return this.video_quality;
    }
    
    public void setVideo_quality(Integer video_quality) {
        this.video_quality = video_quality;
    }
    /**       
     *      * 关键帧间隔
     */

    public Integer getSecond_per_key() {
        return this.second_per_key;
    }
    
    public void setSecond_per_key(Integer second_per_key) {
        this.second_per_key = second_per_key;
    }
   








}
