package com.jwzt.DB.cdn.mount;
// Generated 2006-6-6 14:24:18 by Hibernate Tools 3.1.0 beta3

import com.jwzt.DB.cdn.serverGroup.ILiveServerGroup;
import com.jwzt.DB.cdn.serverGroup.ServerGroupInfo;


/**
 * MountInfo generated by hbm2java
 */

public class MountInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 发布点ID
     */
     private Integer server_mount_id;
     /**
      * 发布点名称
     */
     private String server_mount_name;
     /**
      * 服务器组ID
     */
     private ILiveServerGroup server_group;
     /**
      * 分配的存储空间（0:无限制）
     */
     private Integer storage_space;
     /**
      * 已使用空间（单位：M）
     */
     private Integer used_space;
     /**
      * 发布点对应真实路径
     */
     private String base_path;
     /**
      * FTP路径
     */
     private String ftp_path;
     /**
      * 发布点类型  0：存储发布点  1：分发发布点 
     */
     private Integer mount_type;
     /**
      * 镜像、影子发布点ID
     */
     private Integer mirror_mount_id;
     /**
      * 发布点描述
     */
     private String mount_desc;
     /**
      * 是否正在使用 0：正在使用 1：作废
     */
     private Integer if_use;
     
     /**
      * 公共磁盘空间
     */
     private Integer public_disk_space;
     
     /**
      * 警戒磁盘空间
     */
     private Integer warning_space;
     
     /**
      * 剩余磁盘空间
     */
     private Integer left_space;

     private Integer iscut;
     
 	// 是否是默认访问方式
 	private  Integer isDefault;

    // Constructors

    public Integer getLeft_space() {
		return left_space;
	}

	public void setLeft_space(Integer left_space) {
		this.left_space = left_space;
	}

	public Integer getPublic_disk_space() {
		return public_disk_space;
	}

	public void setPublic_disk_space(Integer public_disk_space) {
		this.public_disk_space = public_disk_space;
	}

	public Integer getWarning_space() {
		return warning_space;
	}

	public void setWarning_space(Integer warning_space) {
		this.warning_space = warning_space;
	}

	/** default constructor */
    public MountInfo() {
    }

	/** minimal constructor */
    public MountInfo(Integer server_mount_id) {
        this.server_mount_id = server_mount_id;
    }
    
    /** full constructor */
    public MountInfo(Integer server_mount_id, String server_mount_name, Integer storage_space, Integer used_space, String base_path, String ftp_path, Integer mount_type, Integer mirror_mount_id, String mount_desc, Integer if_use) {
        this.server_mount_id = server_mount_id;
        this.server_mount_name = server_mount_name;
        this.storage_space = storage_space;
        this.used_space = used_space;
        this.base_path = base_path;
        this.ftp_path = ftp_path;
        this.mount_type = mount_type;
        this.mirror_mount_id = mirror_mount_id;
        this.mount_desc = mount_desc;
        this.if_use = if_use;
    }
    

   
    // Property accessors
    /**       
     *      * 发布点ID
     */

    public Integer getServer_mount_id() {
        return this.server_mount_id;
    }
    
    public void setServer_mount_id(Integer server_mount_id) {
        this.server_mount_id = server_mount_id;
    }
    /**       
     *      * 发布点名称
     */

    public String getServer_mount_name() {
        return this.server_mount_name;
    }
    
    public void setServer_mount_name(String server_mount_name) {
        this.server_mount_name = server_mount_name;
    }
    
    /**       
     *      * 分配的存储空间（0:无限制）
     */
    public Integer getStorage_space() {
        return this.storage_space;
    }
    
    public ILiveServerGroup getServer_group() {
		return server_group;
	}

	public void setServer_group(ILiveServerGroup server_group) {
		this.server_group = server_group;
	}

	public void setStorage_space(Integer storage_space) {
        this.storage_space = storage_space;
    }
    /**       
     *      * 已使用空间（单位：M）
     */

    public Integer getUsed_space() {
        return this.used_space;
    }
    
    public void setUsed_space(Integer used_space) {
        this.used_space = used_space;
    }
    /**       
     *      * 发布点对应真实路径
     */

    public String getBase_path() {
        return this.base_path;
    }
    
    public void setBase_path(String base_path) {
        this.base_path = base_path;
    }
    /**       
     *      * FTP路径
     */

    public String getFtp_path() {
        return this.ftp_path;
    }
    
    public void setFtp_path(String ftp_path) {
        this.ftp_path = ftp_path;
    }
    /**       
     *      * 发布点类型  0：存储发布点  1：分发发布点 2：镜像发布点 3：影子发布点
     */

    public Integer getMount_type() {
        return this.mount_type;
    }
    
    public void setMount_type(Integer mount_type) {
        this.mount_type = mount_type;
    }
    /**       
     *      * 镜像、影子发布点ID
     */

    public Integer getMirror_mount_id() {
        return this.mirror_mount_id;
    }
    
    public void setMirror_mount_id(Integer mirror_mount_id) {
        this.mirror_mount_id = mirror_mount_id;
    }
    /**       
     *      * 发布点描述
     */

    public String getMount_desc() {
        return this.mount_desc;
    }
    
    public void setMount_desc(String mount_desc) {
        this.mount_desc = mount_desc;
    }
    /**       
     *      * 是否正在使用 0：正在使用 1：作废
     */

    public Integer getIf_use() {
        return this.if_use;
    }
    
    public void setIf_use(Integer if_use) {
        this.if_use = if_use;
    }

	public Integer getIscut() {
		return iscut;
	}

	public void setIscut(Integer iscut) {
		this.iscut = iscut;
	}

	public Integer getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}
   








}
