package com.jwzt.DB.common.pk;
// Generated 2006-6-6 14:24:17 by Hibernate Tools 3.1.0 beta3



/**
 * PKInfo generated by hbm2java
 */

public class PKInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 表名
     */
     private String table_name;
     /**
      * 表中的主键名
     */
     private String column_name;
     /**
      * 下一个主键ID
     */
     private Integer next_pk_id;


    // Constructors

    /** default constructor */
    public PKInfo() {
    }

    
    /** full constructor */
    public PKInfo(String table_name, String column_name, Integer next_pk_id) {
        this.table_name = table_name;
        this.column_name = column_name;
        this.next_pk_id = next_pk_id;
    }
    

   
    // Property accessors
    /**       
     *      * 表名
     */

    public String getTable_name() {
        return this.table_name;
    }
    
    public void setTable_name(String table_name) {
        this.table_name = table_name;
    }
    /**       
     *      * 表中的主键名
     */

    public String getColumn_name() {
        return this.column_name;
    }
    
    public void setColumn_name(String column_name) {
        this.column_name = column_name;
    }
    /**       
     *      * 下一个主键ID
     */

    public Integer getNext_pk_id() {
        return this.next_pk_id;
    }
    
    public void setNext_pk_id(Integer next_pk_id) {
        this.next_pk_id = next_pk_id;
    }
   








}
