package com.jwzt.DB.soms.live.proFile;
// Generated 2006-6-6 14:24:18 by Hibernate Tools 3.1.0 beta3



/**
 * ProFileInfo generated by hbm2java
 */

public class ProFileInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一ID
     */
     private Integer profile_id;
     /**
      * 配置文件名称
     */
     private String profile_name;
     /**
      * 视频还是音频
     */
     private Integer ifvideo;
     /**
      * 音频配置id  可否与原vams_audio_conf关连
     */
     private Integer audio_conf_id;
     /**
      * 音频配置名称
     */
     private String video_code_name;
     /**
      * 窗口id
     */
     private Integer win_id;
     /**
      * 视频ids
     */
     private String video_conf_ids;
     /**
      * 配置文件描述
     */
     private String profile_desc;

 	/**
 	 * 站点id
 	 */
 	private Integer site_id;

 	public Integer getSite_id() {
 		return site_id;
 	}

 	public void setSite_id(Integer site_id) {
 		this.site_id = site_id;
 	}

    // Constructors

    /** default constructor */
    public ProFileInfo() {
    }

	/** minimal constructor */
    public ProFileInfo(Integer profile_id, String profile_name) {
        this.profile_id = profile_id;
        this.profile_name = profile_name;
    }
    
    /** full constructor */
    public ProFileInfo(Integer profile_id, String profile_name, Integer ifvideo, Integer audio_conf_id, String video_code_name, Integer win_id, String video_conf_ids, String profile_desc) {
        this.profile_id = profile_id;
        this.profile_name = profile_name;
        this.ifvideo = ifvideo;
        this.audio_conf_id = audio_conf_id;
        this.video_code_name = video_code_name;
        this.win_id = win_id;
        this.video_conf_ids = video_conf_ids;
        this.profile_desc = profile_desc;
    }
    

   
    // Property accessors
    /**       
     *      * 唯一ID
     */

    public Integer getProfile_id() {
        return this.profile_id;
    }
    
    public void setProfile_id(Integer profile_id) {
        this.profile_id = profile_id;
    }
    /**       
     *      * 配置文件名称
     */

    public String getProfile_name() {
        return this.profile_name;
    }
    
    public void setProfile_name(String profile_name) {
        this.profile_name = profile_name;
    }
    /**       
     *      * 视频还是音频
     */

    public Integer getIfvideo() {
        return this.ifvideo;
    }
    
    public void setIfvideo(Integer ifvideo) {
        this.ifvideo = ifvideo;
    }
    /**       
     *      * 音频配置id  可否与原vams_audio_conf关连
     */

    public Integer getAudio_conf_id() {
        return this.audio_conf_id;
    }
    
    public void setAudio_conf_id(Integer audio_conf_id) {
        this.audio_conf_id = audio_conf_id;
    }
    /**       
     *      * 音频配置名称
     */

    public String getVideo_code_name() {
        return this.video_code_name;
    }
    
    public void setVideo_code_name(String video_code_name) {
        this.video_code_name = video_code_name;
    }
    /**       
     *      * 窗口id
     */

    public Integer getWin_id() {
        return this.win_id;
    }
    
    public void setWin_id(Integer win_id) {
        this.win_id = win_id;
    }
    /**       
     *      * 视频ids
     */

    public String getVideo_conf_ids() {
        return this.video_conf_ids;
    }
    
    public void setVideo_conf_ids(String video_conf_ids) {
        this.video_conf_ids = video_conf_ids;
    }
    /**       
     *      * 配置文件描述
     */

    public String getProfile_desc() {
        return this.profile_desc;
    }
    
    public void setProfile_desc(String profile_desc) {
        this.profile_desc = profile_desc;
    }
   








}
