package com.jwzt.DB.soms.live.tvInfo;
// Generated 2006-6-6 14:24:16 by Hibernate Tools 3.1.0 beta3



/**
 * CodeFlowInfo generated by hbm2java
 */

public class TvInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一ID
     */
     private Integer pkid;
     /**
      * 频道tvid
     */
     private Integer tvid;
     /**
      *频道tv名称 
      */
     private String tvName ;
     /**
  	 * 站点id
  	 */
  	private Integer site_id;
  	
	public Integer getSite_id() {
		return site_id;
	}
	public void setSite_id(Integer site_id) {
		this.site_id = site_id;
	}
	public Integer getPkid() {
		return pkid;
	}
	public void setPkid(Integer pkid) {
		this.pkid = pkid;
	}
	public Integer getTvid() {
		return tvid;
	}
	public void setTvid(Integer tvid) {
		this.tvid = tvid;
	}
	public String getTvName() {
		return tvName;
	}
	public void setTvName(String tvName) {
		this.tvName = tvName;
	}
}
