package com.jwzt.DB.soms.live.proFile;
// Generated 2006-6-6 14:24:15 by Hibernate Tools 3.1.0 beta3



/**
 * LiveAudioCodeInfo generated by hbm2java
 */

public class LiveAudioCodeInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一ID
     */
     private Integer audio_conf_id;
     /**
      * 音频编码配置名
     */
     private String audio_conf_name;
     /**
      * 音频编码名
     */
     private String audio_code_name;


    // Constructors

    /** default constructor */
    public LiveAudioCodeInfo() {
    }

	/** minimal constructor */
    public LiveAudioCodeInfo(Integer audio_conf_id) {
        this.audio_conf_id = audio_conf_id;
    }
    
    /** full constructor */
    public LiveAudioCodeInfo(Integer audio_conf_id, String audio_conf_name, String audio_code_name) {
        this.audio_conf_id = audio_conf_id;
        this.audio_conf_name = audio_conf_name;
        this.audio_code_name = audio_code_name;
    }
    

   
    // Property accessors
    /**       
     *      * 唯一ID
     */

    public Integer getAudio_conf_id() {
        return this.audio_conf_id;
    }
    
    public void setAudio_conf_id(Integer audio_conf_id) {
        this.audio_conf_id = audio_conf_id;
    }
    /**       
     *      * 音频编码配置名
     */

    public String getAudio_conf_name() {
        return this.audio_conf_name;
    }
    
    public void setAudio_conf_name(String audio_conf_name) {
        this.audio_conf_name = audio_conf_name;
    }
    /**       
     *      * 音频编码名
     */

    public String getAudio_code_name() {
        return this.audio_code_name;
    }
    
    public void setAudio_code_name(String audio_code_name) {
        this.audio_code_name = audio_code_name;
    }
   








}
