package com.jwzt.DB.soms.live.proFile;
// Generated 2006-6-6 14:24:18 by Hibernate Tools 3.1.0 beta3



/**
 * LiveVideoWinInfo generated by hbm2java
 */

public class LiveVideoWinInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一ID
     */
     private Integer win_id;
     /**
      * 窗口的高
     */
     private Integer win_h;
     /**
      * 窗口的宽
     */
     private Integer win_w;


    // Constructors

    /** default constructor */
    public LiveVideoWinInfo() {
    }

	/** minimal constructor */
    public LiveVideoWinInfo(Integer win_id) {
        this.win_id = win_id;
    }
    
    /** full constructor */
    public LiveVideoWinInfo(Integer win_id, Integer win_h, Integer win_w) {
        this.win_id = win_id;
        this.win_h = win_h;
        this.win_w = win_w;
    }
    

   
    // Property accessors
    /**       
     *      * 唯一ID
     */

    public Integer getWin_id() {
        return this.win_id;
    }
    
    public void setWin_id(Integer win_id) {
        this.win_id = win_id;
    }
    /**       
     *      * 窗口的高
     */

    public Integer getWin_h() {
        return this.win_h;
    }
    
    public void setWin_h(Integer win_h) {
        this.win_h = win_h;
    }
    /**       
     *      * 窗口的宽
     */

    public Integer getWin_w() {
        return this.win_w;
    }
    
    public void setWin_w(Integer win_w) {
        this.win_w = win_w;
    }
   








}
