package com.jwzt.DB.soms.live.liveChannel.shift;

// Generated 2006-6-6 14:24:16 by Hibernate Tools 3.1.0 beta3

import java.sql.Timestamp;

/**
 * ChannelInfo generated by hbm2java
 */

public class ChannelInfoShift implements java.io.Serializable
{

	// Fields

	/**
	 * 唯一ID
	 */
	private Integer channel_id;

	/**
	 * 频道所属的电视台（备用）
	 */
	private Integer LiveTypeHigh=0;

	/**
	 * 直播发布点所在的服务器组ID
	 */
	private Integer LiveTypeLow=0;

	/**
	 * 直播发布点名称
	 */
	private String channel_mountPath;

	/**
	 * 频道类型 0：采集直播 1：虚拟直播 2：混和直播(单码流) 3：混和直播(多码流)
	 */
	private Integer channel_mount_id;

	private String channel_programPathHigh="";

	/**
	 * 直播认证地址
	 */
	private String channel_programPathLow="";

	private String channel_durationHigh="";

	/**
	 * 远程发布点地址
	 */
	private String channel_durationLow="";
	
	/**
	 * 时移创建时间
	 */
	private String channel_create_time = "";
	
	private String record_time = "";

	public String getChannel_durationHigh() {
		return channel_durationHigh;
	}

	public void setChannel_durationHigh(String channel_durationHigh) {
		this.channel_durationHigh = channel_durationHigh;
	}

	public String getChannel_durationLow() {
		return channel_durationLow;
	}

	public void setChannel_durationLow(String channel_durationLow) {
		this.channel_durationLow = channel_durationLow;
	}

	public Integer getChannel_id() {
		return channel_id;
	}

	public void setChannel_id(Integer channel_id) {
		this.channel_id = channel_id;
	}

	public Integer getChannel_mount_id() {
		return channel_mount_id;
	}

	public void setChannel_mount_id(Integer channel_mount_id) {
		this.channel_mount_id = channel_mount_id;
	}

	public String getChannel_mountPath() {
		return channel_mountPath;
	}

	public void setChannel_mountPath(String channel_mountPath) {
		this.channel_mountPath = channel_mountPath;
	}

	public String getChannel_programPathHigh() {
		return channel_programPathHigh;
	}

	public void setChannel_programPathHigh(String channel_programPathHigh) {
		this.channel_programPathHigh = channel_programPathHigh;
	}

	public String getChannel_programPathLow() {
		return channel_programPathLow;
	}

	public void setChannel_programPathLow(String channel_programPathLow) {
		this.channel_programPathLow = channel_programPathLow;
	}

	public Integer getLiveTypeHigh() {
		return LiveTypeHigh;
	}

	public void setLiveTypeHigh(Integer liveTypeHigh) {
		LiveTypeHigh = liveTypeHigh;
	}

	public Integer getLiveTypeLow() {
		return LiveTypeLow;
	}

	public void setLiveTypeLow(Integer liveTypeLow) {
		LiveTypeLow = liveTypeLow;
	}

	public String getChannel_create_time() {
		return channel_create_time;
	}

	public void setChannel_create_time(String channel_create_time) {
		this.channel_create_time = channel_create_time;
	}

	public String getRecord_time() {
		return record_time;
	}

	public void setRecord_time(String record_time) {
		this.record_time = record_time;
	}

	
}
