package com.jwzt.DB.soms.live.liveProgram;
// Generated 2006-6-6 14:24:18 by Hibernate Tools 3.1.0 beta3

import com.jwzt.DB.soms.live.liveChannel.ChannelInfo;
import com.jwzt.DB.soms.live.proFile.ProFileInfo;
import com.jwzt.DB.soms.vod.file.FileInfo;
import java.sql.Timestamp;


/**
 * ProgramInfo generated by hbm2java
 */

public class ProgramInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 唯一id
     */
     private Integer program_id;
     /**
      * 节目名称
     */
     private String program_name;
     /**
      * 频道id
     */
     private ChannelInfo channelInfo;
     /**
      * 节目的顺序，数值大的排在前面
     */
     private Integer program_order;
     /**
      * 是否加密（0：不加密  1：加密），继承表soms4_live_channel中的if_drm字段
     */
     private String if_drm;
     /**
      * 配置文件id 继承表soms4_live_channel中的profile_id字段
     */
     private ProFileInfo proFileInfo;
     /**
      * 节目时长
     */
     private Integer time_long;
     /**
      * 开始时间
     */
     private Timestamp start_time;
     /**
      * 结束时间
      */
     private Timestamp end_time;
     /**
      * 0:文件直播 1:直播
     */
     private Integer play_type;
     /**
      * 文件直播：文件id
     */
     private FileInfo fileInfo;
     /**
      * 文件存储计划id
     */
     private Integer save_plan_id;
     /**
      * 播放周期 0:无周期 1:有周期
     */
     private Integer cycle;
     /**
      * 星期的字符串
     */
     private String cycle_ids;
     /**
      * 节目描述
     */
     private String prog_desc;
     
     /**
      * 远程流地址
      */
     private String remote_address;

     /**
      * 节目单所属的电台id
      */
     private String program_tvid;
    // Constructors
     /**
      * 节目单所属的电台名称
      */
     private String tvName;
     
     /**
      * 节目单是否失效    0 是生效  1 是失效
      */
     private int invalid=0;
   
	public String getProgram_tvid() {
		return program_tvid;
	}

	public void setProgram_tvid(String program_tvid) {
		this.program_tvid = program_tvid;
	}

	/** default constructor */
    public ProgramInfo() {
    }

	/** minimal constructor */
    public ProgramInfo(Integer program_id, String program_name) {
        this.program_id = program_id;
        this.program_name = program_name;
    }
    
    /** full constructor */
    public ProgramInfo(Integer program_id, String program_name, ChannelInfo channelInfo, Integer program_order, String if_drm, ProFileInfo proFileInfo, Integer time_long, Timestamp start_time, Integer play_type, FileInfo fileInfo, Integer save_plan_id, Integer cycle, String cycle_ids, String prog_desc) {
        this.program_id = program_id;
        this.program_name = program_name;
        this.channelInfo = channelInfo;
        this.program_order = program_order;
        this.if_drm = if_drm;
        this.proFileInfo = proFileInfo;
        this.time_long = time_long;
        this.start_time = start_time;
        this.play_type = play_type;
        this.fileInfo = fileInfo;
        this.save_plan_id = save_plan_id;
        this.cycle = cycle;
        this.cycle_ids = cycle_ids;
        this.prog_desc = prog_desc;
    }
    

   
    // Property accessors
    /**       
     *      * 唯一id
     */

    public Integer getProgram_id() {
        return this.program_id;
    }
    
    public void setProgram_id(Integer program_id) {
        this.program_id = program_id;
    }
    /**       
     *      * 节目名称
     */

    public String getProgram_name() {
        return this.program_name;
    }
    
    public void setProgram_name(String program_name) {
        this.program_name = program_name;
    }
    /**       
     *      * 频道id
     */

    public ChannelInfo getChannelInfo() {
        return this.channelInfo;
    }
    
    public void setChannelInfo(ChannelInfo channelInfo) {
        this.channelInfo = channelInfo;
    }
    /**       
     *      * 节目的顺序，数值大的排在前面
     */

    public Integer getProgram_order() {
        return this.program_order;
    }
    
    public void setProgram_order(Integer program_order) {
        this.program_order = program_order;
    }
    /**       
     *      * 是否加密（0：不加密  1：加密），继承表soms4_live_channel中的if_drm字段
     */

    public String getIf_drm() {
        return this.if_drm;
    }
    
    public void setIf_drm(String if_drm) {
        this.if_drm = if_drm;
    }
    /**       
     *      * 配置文件id 继承表soms4_live_channel中的profile_id字段
     */

    public ProFileInfo getProFileInfo() {
        return this.proFileInfo;
    }
    
    public void setProFileInfo(ProFileInfo proFileInfo) {
        this.proFileInfo = proFileInfo;
    }
    /**       
     *      * 节目时长
     */

    public Integer getTime_long() {
        return this.time_long;
    }
    
    public void setTime_long(Integer time_long) {
        this.time_long = time_long;
    }
    /**       
     *      * 开始时间
     */

    public Timestamp getStart_time() {
        return this.start_time;
    }
    
    public void setStart_time(Timestamp start_time) {
        this.start_time = start_time;
    }
    /**       
     *      * 0:文件直播 1:直播
     */

    public Integer getPlay_type() {
        return this.play_type;
    }
    
    public void setPlay_type(Integer play_type) {
        this.play_type = play_type;
    }
    /**       
     *      * 文件直播：文件id
     */

    public FileInfo getFileInfo() {
        return this.fileInfo;
    }
    
    public void setFileInfo(FileInfo fileInfo) {
        this.fileInfo = fileInfo;
    }
    /**       
     *      * 文件存储计划id
     */

    public Integer getSave_plan_id() {
        return this.save_plan_id;
    }
    
    public void setSave_plan_id(Integer save_plan_id) {
        this.save_plan_id = save_plan_id;
    }
    /**       
     *      * 播放周期 0:无周期 1:有周期
     */

    public Integer getCycle() {
        return this.cycle;
    }
    
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }
    /**       
     *      * 星期的字符串
     */

    public String getCycle_ids() {
        return this.cycle_ids;
    }
    
    public void setCycle_ids(String cycle_ids) {
        this.cycle_ids = cycle_ids;
    }
    /**       
     *      * 节目描述
     */

    public String getProg_desc() {
        return this.prog_desc;
    }
    
    public void setProg_desc(String prog_desc) {
        this.prog_desc = prog_desc;
    }

	public String getRemote_address() {
		return remote_address;
	}

	public void setRemote_address(String remote_address) {
		this.remote_address = remote_address;
	}

	public Timestamp getEnd_time() {
		return end_time;
	}

	public void setEnd_time(Timestamp end_time) {
		this.end_time = end_time;
	}

	public String getTvName() {
		return tvName;
	}

	public void setTvName(String tvName) {
		this.tvName = tvName;
	}

	public int getInvalid() {
		return invalid;
	}

	public void setInvalid(int invalid) {
		this.invalid = invalid;
	}
   

}
