package com.jwzt.DB.soms.vod.catalog;
// Generated 2006-6-6 14:24:16 by Hibernate Tools 3.1.0 beta3

import com.jwzt.DB.cdn.mount.MountInfo;


/**
 * CatalogInfo generated by hbm2java
 */

public class CatalogInfo  implements java.io.Serializable {


    // Fields    

     /**
      * 栏目ID
     */
     private Integer catalog_id;
     /**
      * 栏目名称
     */
     private String catalog_name;
     /**
      * 栏目类型 点播(0) 广告(1)
     */
     private Integer catalog_type;
     /**
      * 栏目类型 使用状态(0) 预删除状态(1)
     */
     private Integer catalog_state;
     /**
      * 父栏目ID 0表示一级栏目
     */
     private Integer parent_id;
     
     /**
      * 临时记录父栏目ID  xhf+ 2009-10 
     */
     private Integer parent_id_temp;
     /**
      * 用于设置节点显示顺序  xhf+ 2009-10 
     */
     private Integer node_archive_day;
     
     /**
      * 根栏目ID
     */
     private Integer root_id;
     /**
      * 发布点ID
     */
     private MountInfo mountInfo;
     /**
      * 栏目属性
     */
     private Integer attr;
     /**
      * 图片路径
     */
     private String tree_images;
     /**
      * 栏目描述
     */
     private String catalog_desc;

     /**
      * 站点id
      */
     private Integer site_id;
    // Constructors

    public Integer getSite_id() {
		return site_id;
	}

	public void setSite_id(Integer site_id) {
		this.site_id = site_id;
	}

	/** default constructor */
    public CatalogInfo() {
    }

	/** minimal constructor */
    public CatalogInfo(Integer catalog_id, String catalog_name) {
        this.catalog_id = catalog_id;
        this.catalog_name = catalog_name;
    }
    
    /** full constructor */
    public CatalogInfo(Integer catalog_id, String catalog_name, Integer catalog_type, Integer catalog_state, Integer parent_id, Integer root_id, MountInfo mountInfo, Integer attr, String tree_images, String catalog_desc, Integer parent_id_temp, Integer node_archive_day) {
        this.catalog_id = catalog_id;
        this.catalog_name = catalog_name;
        this.catalog_type = catalog_type;
        this.catalog_state = catalog_state;
        this.parent_id = parent_id;
        this.root_id = root_id;
        this.mountInfo = mountInfo;
        this.attr = attr;
        this.tree_images = tree_images;
        this.catalog_desc = catalog_desc;
        this.parent_id_temp = parent_id_temp;
        this.node_archive_day = node_archive_day;
    }
    

   
    // Property accessors
    /**       
     *      * 栏目ID
     */

    public Integer getCatalog_id() {
        return this.catalog_id;
    }
    
    public void setCatalog_id(Integer catalog_id) {
        this.catalog_id = catalog_id;
    }
    /**       
     *      * 栏目名称
     */

    public String getCatalog_name() {
        return this.catalog_name;
    }
    
    public void setCatalog_name(String catalog_name) {
        this.catalog_name = catalog_name;
    }
    /**       
     *      * 栏目类型 点播(0) 广告(1)
     */

    public Integer getCatalog_type() {
        return this.catalog_type;
    }
    
    public void setCatalog_type(Integer catalog_type) {
        this.catalog_type = catalog_type;
    }
    /**       
     *      * 栏目类型 使用状态(0) 预删除状态(1)
     */

    public Integer getCatalog_state() {
        return this.catalog_state;
    }
    
    public void setCatalog_state(Integer catalog_state) {
        this.catalog_state = catalog_state;
    }
    /**       
     *      * 父栏目ID 0表示一级栏目
     */

    public Integer getParent_id() {
        return this.parent_id;
    }
    
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }
    /**       
     *      * 根栏目ID
     */

    public Integer getRoot_id() {
        return this.root_id;
    }
    
    public void setRoot_id(Integer root_id) {
        this.root_id = root_id;
    }
    /**       
     *      * 发布点ID
     */

    public MountInfo getMountInfo() {
        return this.mountInfo;
    }
    
    public void setMountInfo(MountInfo mountInfo) {
        this.mountInfo = mountInfo;
    }
    /**       
     *      * 栏目属性
     */

    public Integer getAttr() {
        return this.attr;
    }
    
    public void setAttr(Integer attr) {
        this.attr = attr;
    }
    /**       
     *      * 图片路径
     */

    public String getTree_images() {
        return this.tree_images;
    }
    
    public void setTree_images(String tree_images) {
        this.tree_images = tree_images;
    }
    /**       
     *      * 栏目描述
     */

    public String getCatalog_desc() {
        return this.catalog_desc;
    }
    
    public void setCatalog_desc(String catalog_desc) {
        this.catalog_desc = catalog_desc;
    }
   

    public static final int VOD_CATALOG 	= 1;
    public static final int AD_CATALOG 		= 2;
    public static final int LIVE_CATALOG 	= 3;
    
    /**       
     *      * 临时父栏目ID 
     */
	public Integer getParent_id_temp() {
		return parent_id_temp;
	}

	public void setParent_id_temp(Integer parent_id_temp) {
		this.parent_id_temp = parent_id_temp;
	}

    /**       
     *      * 用于设置节点显示顺序
     */
	public Integer getNode_archive_day() {
		return node_archive_day;
	}

	public void setNode_archive_day(Integer node_archive_day) {
		this.node_archive_day = node_archive_day;
	}




}
